
// This file is automatically generated. Do not edit it directly.
import { createBrowserClient } from '@/utils/supabase/browserClient';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createBrowserClient();
